import { Customer, Company, DetectionRule, RecoveryPlan, DashboardMetrics, ReportSummary } from '../types';

export const FALLBACK_METRICS: DashboardMetrics = {
  totalCustomers: 6,
  atRiskCount: 2,
  recoveringCount: 1,
  retainedCount: 3,
  totalArr: 48500000,
  savedArr: 16920000,
  activeWorkflows: 2,
};

export const FALLBACK_CUSTOMERS: Customer[] = [
  {
    id: 'c-101',
    externalCustomerId: 'SB-CIB-1001',
    name: 'Shoprite Holdings Ltd',
    email: 'treasury@shoprite.co.za',
    mrr: 1250000,
    arr: 15000000,
    healthScore: 32,
    churnProbability: 88,
    status: 'AT_RISK',
    companyId: 'comp-sb-01',
    companyName: 'Standard Bank Corporate & Investment Banking',
    riskFactor: '45% drop in transaction volume (30 days)',
    notes: 'Immediate relationship manager outreach triggered via BPMN workflow.',
  },
  {
    id: 'c-102',
    externalCustomerId: 'SB-CIB-1002',
    name: 'MTN Group Corporate',
    email: 'finance@mtn.com',
    mrr: 950000,
    arr: 11400000,
    healthScore: 48,
    churnProbability: 72,
    status: 'AT_RISK',
    companyId: 'comp-sb-01',
    companyName: 'Standard Bank Corporate & Investment Banking',
    riskFactor: 'Competitive RFP issued for forex clearing',
    notes: 'Offer 15% pricing discount on cross-border liquidity management.',
  },
  {
    id: 'c-103',
    externalCustomerId: 'SB-CIB-1003',
    name: 'Sasol Energy Treasury',
    email: 'treasury@sasol.com',
    mrr: 1410000,
    arr: 16920000,
    healthScore: 65,
    churnProbability: 40,
    status: 'RECOVERING',
    companyId: 'comp-sb-01',
    companyName: 'Standard Bank Corporate & Investment Banking',
    riskFactor: 'Executive churn risk resolved - discount applied',
    notes: 'Recovery workflow active; contract extension pending signature.',
  },
  {
    id: 'c-104',
    externalCustomerId: 'SB-CIB-1004',
    name: 'Discovery Limited Corporate',
    email: 'treasury@discovery.co.za',
    mrr: 880000,
    arr: 10560000,
    healthScore: 92,
    churnProbability: 8,
    status: 'HEALTHY',
    companyId: 'comp-sb-01',
    companyName: 'Standard Bank Corporate & Investment Banking',
    riskFactor: 'None',
    notes: 'Strong engagement across prime brokerage & cash management.',
  },
  {
    id: 'c-105',
    externalCustomerId: 'SB-CIB-1005',
    name: 'Naspers Corporate Finance',
    email: 'invest@naspers.com',
    mrr: 2100000,
    arr: 25200000,
    healthScore: 89,
    churnProbability: 11,
    status: 'RETAINED',
    companyId: 'comp-sb-01',
    companyName: 'Standard Bank Corporate & Investment Banking',
    riskFactor: 'Retained via bespoke multi-currency trade facility',
    notes: 'Successfully renewed 3-year mandate.',
  },
];

export const FALLBACK_COMPANIES: Company[] = [
  {
    id: 'comp-sb-01',
    name: 'Standard Bank Corporate & Investment Banking',
    domain: 'standardbank.co.za',
    tenantId: 'TENANT-SB-CIB',
    customerCount: 6,
  },
];

export const FALLBACK_DETECTION_RULES: DetectionRule[] = [
  {
    id: 'rule-101',
    ruleName: 'Corporate Transaction Volume Drop (>40%)',
    metricType: 'TRANSACTION_VOLUME_DROP_45_PCT',
    thresholdValue: 40.0,
    timeframeDays: 30,
    severity: 'CRITICAL',
    enabled: true,
    description: 'Triggers when a corporate client decreases transaction clearing volume by >40% over 30 days.',
  },
  {
    id: 'rule-102',
    ruleName: 'Relationship Manager Activity Inactive (>21 days)',
    metricType: 'RM_INACTIVITY',
    thresholdValue: 21.0,
    timeframeDays: 21,
    severity: 'HIGH',
    enabled: true,
    description: 'Flags accounts where no executive touchpoint or RM call log was recorded for 3 weeks.',
  },
];

export const FALLBACK_RECOVERY_PLANS: RecoveryPlan[] = [
  {
    id: 'plan-201',
    customerId: 'c-101',
    customerName: 'Shoprite Holdings Ltd',
    recommendedAction: 'Apply 15% Pricing Discount & Schedule Executive CIB Review',
    discountPercentage: 15,
    status: 'PENDING_APPROVAL',
    workflowInstanceId: 'camunda-wf-10001',
    assignedManager: 'admin@standardbank.co.za',
    createdAt: '2026-09-10T14:30:00Z',
  },
  {
    id: 'plan-202',
    customerId: 'c-102',
    customerName: 'MTN Group Corporate',
    recommendedAction: 'Schedule Executive Lunch & Fee Restructuring Proposal',
    discountPercentage: 10,
    status: 'APPROVED',
    workflowInstanceId: 'camunda-wf-10002',
    assignedManager: 'rm.lead@standardbank.co.za',
    createdAt: '2026-09-09T09:15:00Z',
  },
];

export const FALLBACK_REPORTS: ReportSummary = {
  totalArrAtRisk: 26400000,
  totalArrSaved: 16920000,
  monthlyChurnTrend: [
    { month: 'Apr', atRiskCount: 4, savedCount: 3 },
    { month: 'May', atRiskCount: 5, savedCount: 4 },
    { month: 'Jun', atRiskCount: 3, savedCount: 3 },
    { month: 'Jul', atRiskCount: 6, savedCount: 5 },
    { month: 'Aug', atRiskCount: 4, savedCount: 4 },
    { month: 'Sep', atRiskCount: 2, savedCount: 1 },
  ],
  riskBySegment: [
    { segment: 'Retail Banking', count: 1 },
    { segment: 'Corporate & Investment Banking (CIB)', count: 2 },
    { segment: 'Wealth & Investment', count: 0 },
  ],
};
